/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface PageResult {
    /**
     * Gets the size of the paginated result.
     */
    size: number;
    /**
     * Gets the total items of the paginated result.
     */
    totalItems: number;
    /**
     * Gets the total pages of the paginated result.
     */
    totalPages: number;
    /**
     * Gets the current page of the paginated result.
     */
    currentPage: number;
}
