/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface RoomId {
    /**
     * Gets the underlying System.Guid value if set, otherwise a Vogen.ValueObjectValidationException is thrown.
     */
    readonly value: string;
}
