/**
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageResult } from './pageResult';
import { Session } from './session';

export interface SessionItemsResult {
    /**
     * Gets the items.
     */
    items: Array<Session>;
    pages: PageResult;
}
