ARG DOTNET_VERSION=9.0

FROM mcr.microsoft.com/dotnet/aspnet:${DOTNET_VERSION} AS base
WORKDIR /app

ARG PROJECT_NAME=Backend.WebApi

COPY . .

EXPOSE 80

ENV ASPNETCORE_URLS="http://+:80"

ENTRYPOINT ["dotnet", "RioScaffolding.OpenSpacePlanner.Backend.WebApi.dll"]
