parameters:
    - name: pullEnable
      type: boolean
      default: true

    - name: pullRegistry
      type: string
      default: ''

    - name: pushRegistry
      type: string

    - name: imageName
      type: string
      default: ''

    - name: imageTag
      type: string
      default: ''

steps:
    - ${{ if or(eq(parameters.pullEnable, true), eq(parameters.pullRegistry, '')) }}:
          - task: Docker@2
            displayName: 'Login to pull registry'
            inputs:
                command: 'login'
                containerRegistry: ${{ parameters.pullRegistry }}

          - script: |
                docker pull ${{ parameters.pullRegistry }}/${{ parameters.imageName }}:${{ coalesce(parameters.imageTag, variables['Build.BuildId']) }}
            displayName: 'Pull image'

          - script: |
                docker tag ${{ parameters.pullRegistry }}/${{ parameters.imageName }}:${{ coalesce(parameters.imageTag, variables['Build.BuildId']) }} ${{ parameters.pushRegistry }}/${{ parameters.imageName }}:${{ coalesce(parameters.imageTag, variables['Build.BuildId']) }}
            displayName: 'Retag image'

    - task: Docker@2
      displayName: 'Login to push registry'
      inputs:
          command: 'login'
          containerRegistry: ${{ parameters.pushRegistry }}

    - task: Docker@2
      displayName: 'Push image'
      inputs:
          command: 'push'
          repository: ${{ parameters.imageName }}
          containerRegistry: ${{ parameters.pushRegistry }}
          tags: |
              ${{ coalesce(parameters.imageTag, variables['Build.BuildId']) }}
